################################################################################
# File: data_control.R                                                         #
# Project: crcsim                                                              #
# Created Date: 2026-02-17                                                     #
# Author: Matthew Carroll                                                      #
# -----                                                                        #
# Last Modified: 2026-08-28                                                    #
# Modified By: Matthew Carroll                                                 #
# -----                                                                        #
# Copyright (c) 2026 Syndemics Lab at Boston Medical Center                    #
################################################################################

#' Data generation tool. This creates a simulated dataset for testing various
#' Capture-Recapture models. The user is able to specify the number of
#' individuals, the number of captures, and optional numerical covariates
#' generated from per-covariate distribution settings. The returned value
#' represents the "raw" simulated data where each row is a single sample.
#' Frequency tables can also be generated by setting
#' \code{return_frequency_table} to \code{TRUE}, which will aggregate identical
#' rows and append a frequency column \code{N_ID}.
#'
#' @param n_individuals int: number of participants to simulate
#' @param n_captures int: number of binary capture columns to simulate
#' @param p_captures numeric vector: optional capture probabilities of length
#'   \code{n_captures}. Defaults to 0.5 for each capture column.
#' @param covariate_ranges data.frame: optional covariate specification table
#'   with columns \code{distribution}, \code{p1}, \code{p2}, and \code{dtype}.
#'   Each row defines one numerical covariate named \code{covariate_i}.
#'   Supported distributions are \code{uniform} and \code{normal}. For
#'   \code{uniform}, \code{p1 = low} and \code{p2 = high}. For \code{normal},
#'   \code{p1 = mean} and \code{p2 = standard deviation}.
#' @param return_frequency_table logical: when \code{TRUE}, aggregates identical
#'   rows and appends frequency column \code{N_ID}. Default is \code{FALSE}.
#'
#' @returns a tibble
#'
#' @export
create_data <- function(
    n_individuals,
    n_captures,
    p_captures = NULL,
    covariate_ranges = NULL,
    return_frequency_table = FALSE
) {
    validate_create_args(
        n_individuals = n_individuals,
        n_captures = n_captures,
        covariate_ranges = covariate_ranges,
        return_frequency_table = return_frequency_table
    )

    capture_probs <- normalize_p_captures(
        n_captures = n_captures,
        p_captures = p_captures
    )

    covariate_specs <- normalize_covariate_ranges(
        covariate_ranges = covariate_ranges
    )

    records <- build_individual_records(
        n_individuals = n_individuals,
        capture_probs = capture_probs,
        covariate_specs = covariate_specs
    )

    if (isTRUE(return_frequency_table)) {
        return(build_contingency_table(records))
    }

    return(records)
}

#' Sample Captures for Individuals. This function generates a data frame of
#' simulated capture data for a specified number of individuals and capture
#' probabilities. Each row represents an individual, and each column represents
#' a capture event. The values in the data frame are binary (0 or 1),
#' indicating whether an individual was captured (1) or not (0) for each
#' capture event.
#'
#' @param n_individuals int: The number of individuals to simulate.
#' @param p_captures numeric vector: A vector of capture probabilities for each
#' capture event. The length of this vector determines the number of capture
#' events.
#' @return A data frame where each row represents an individual and each column
#' represents a capture event. The values are binary (0 or 1), indicating
#' whether an individual was captured (1) or not (0) for each capture event.
#'
#' @export
sample_captures <- function(
    n_individuals,
    p_captures
) {
    validate_create_args(
        n_individuals = n_individuals,
        n_captures = length(p_captures),
        covariate_ranges = NULL,
        return_frequency_table = FALSE
    )
    capture_probs <- normalize_p_captures(
        n_captures = length(p_captures),
        p_captures = p_captures
    )

    records <- lapply(seq_len(n_individuals), function(x) {
        return(sample_single_capture(capture_probs))
    })
    records <- as.data.frame(do.call(rbind, records))
    colnames(records) <- paste0("capture_", seq_along(capture_probs))
    return(records)
}

#' Sample Captures Based on Covariates. This function generates a data frame of
#' simulated capture data for a specified number of individuals based on the
#' provided covariate data. Each row represents an individual, and each column
#' represents a capture event. The values in the data frame are binary (0 or 1),
#' indicating whether an individual was captured (1) or not (0) for each
#' capture event. The capture probabilities are determined by the covariate
#' values, specifically the "sex" column, where the probability of capture is
#' higher for one sex compared to the other.
#'
#' @param data_table data.frame: A data frame containing covariate data for each
#' individual. The data frame must contain a "sex" column with binary values (0
#' or 1) indicating the sex of each individual.
#' @param n_cols int: The number of capture columns to generate. Each column
#' represents a capture event.
#' @param covariate_conditions function: function that takes \code{data_table}
#' and returns a numeric probability vector \code{capture_prob} in [0, 1].
#' @return A data frame where each row represents an individual and each column
#' represents a capture event. The values are binary (0 or 1), indicating
#' whether an individual was captured (1) or not (0) for each capture event,
#' based on the covariate values in the input data frame.
#' @export
captures_from_covariates <- function(
    data_table,
    n_cols,
    cov_func
) {
    if (!is.data.frame(data_table)) {
        stop("data_table must be a data.frame")
    }
    if (!is.numeric(n_cols) || length(n_cols) != 1 || n_cols %% 1 != 0) {
        stop("n_cols must be an integer scalar")
    }
    if (!is.function(cov_func)) {
        stop("cov_func must be a function")
    }
    if (n_cols <= 0) {
        return(data_table)
    }

    capture_prob <- cov_func(data_table)
    if (!is.numeric(capture_prob) || length(capture_prob) != nrow(data_table)) {
        stop(paste0(
            "cov_func must return a numeric vector",
            " of length nrow(data_table)"
        ))
    }
    if (any(is.na(capture_prob) | capture_prob < 0 | capture_prob > 1)) {
        stop(paste0(
            "cov_func must return probabilities between",
            " 0 and 1 without NA"
        ))
    }

    capture_cols <- paste0("capture_", seq_len(n_cols))
    for (col in capture_cols) {
        if (!col %in% colnames(data_table)) {
            data_table[[col]] <- as.integer(stats::rbinom(
                n = nrow(data_table),
                size = 1,
                prob = capture_prob
            ))
        }
    }
    return(data_table)
}

#' Default Covariate Conditions for Capture Probability.
#' This function computes \code{capture_prob} from four covariates using a
#' logistic transform.
#'
#' @param data_table data.frame containing columns \code{covariate_1},
#' \code{covariate_2}, \code{covariate_3}, and \code{covariate_4}.
#' @param intercept The intercept value to update the covariates.
#' @return numeric vector \code{capture_prob} with values in (0, 1).
#' @export
covariate_conditions <- function(data_table, intercept = 1) {
    z1_values <- data_table[["covariate_1"]]
    z2_values <- data_table[["covariate_2"]]
    z3_values <- data_table[["covariate_3"]]
    z4_values <- data_table[["covariate_4"]]

    v <- exp(
        intercept +
            0.5 * z1_values +
            0.5 * z2_values -
            0.5 * z3_values -
            0.5 * z4_values
    )

    capture_prob <- v / (1 + v)
    return(capture_prob)
}

#' Sample Captures for a Single Individual. This function generates a binary
#' vector indicating whether an individual was captured (1) or not (0) for each
#' capture event based on the provided capture probabilities.
#'
#' @param capture_probs numeric vector: A vector of capture probabilities for
#' each capture event. The length of this vector determines the number of
#' capture events.
#' @return A binary vector indicating whether the individual was captured (1)
#' or not (0) for each capture event.
#' @importFrom stats rbinom
#' @keywords internal
sample_single_capture <- function(capture_probs) {
    n <- length(capture_probs)
    out <- as.integer(stats::rbinom(n = n, size = 1, prob = capture_probs))
    return(out)
}

#' Apply Suppression to Frequency Table Data.
#' This function takes a frequency table dataset and applies suppression to the
#' frequency column.
#'
#' @param data data.frame: the frequency table dataset to apply suppression to
#' @param suppression_threshold int: the threshold at which to apply
#' suppression.
#' @param freq_col string: the name of the frequency column in the dataset.
#' Default is "N_ID".
#' @return a data.frame with suppression applied to the frequency column
#'
#' @importFrom dplyr mutate
#' @export
suppress_data <- function(data, suppression_threshold, freq_col = "N_ID") {
    if (!is.data.frame(data)) {
        stop("data must be a data.frame")
    }
    if (
        !is.numeric(suppression_threshold) || length(suppression_threshold) != 1
    ) {
        stop("suppression_threshold must be a numeric scalar")
    }
    if (!is.character(freq_col) || length(freq_col) != 1) {
        stop("freq_col must be a single column name")
    }
    if (!freq_col %in% colnames(data)) {
        stop("Frequency column not found in data. Cannot apply suppression.")
    }
    if (!is.numeric(data[[freq_col]])) {
        stop("Frequency column must be numeric")
    }
    data <- dplyr::filter(
        data,
        .data[[freq_col]] > suppression_threshold
    )
    return(data)
}

#' Get Captured Rows
#' @description Function to filter out rows where all capture columns are not 0.
#' This is used to identify all the captured rows in a dataset.
#'
#' @param data_table data.frame: Data frame containing either a frequency table
#' or individual records with capture columns.
#' @param capture character vector: names of capture columns
#' @returns tibble containing only rows where people are captured.
#'
#' @importFrom dplyr filter across
#' @importFrom tibble as_tibble
#' @export
extract_captured_data <- function(data_table, capture) {
    captured_rows <- tibble::as_tibble(data_table) |>
        dplyr::filter(rowSums(dplyr::across(dplyr::all_of(capture))) != 0)
    return(captured_rows)
}

#' Get Uncaptured Rows
#' @description Function to filter out rows where all capture columns are 0.
#' This is used to identify all the uncaptured rows in a dataset, which is
#' necessary for extracting a ground truth value for simulation evaluation.
#'
#' @param data_table data.frame: Data frame containing either a frequency table
#' or individual records with capture columns.
#' @param capture character vector: names of capture columns
#' @returns tibble containing only rows where people are uncaptured.
#'
#' @importFrom dplyr filter across
#' @importFrom tibble as_tibble
#' @export
extract_uncaptured_data <- function(data_table, capture) {
    uncaptured_rows <- tibble::as_tibble(data_table) |>
        dplyr::filter(rowSums(dplyr::across(dplyr::all_of(capture))) == 0)
    return(uncaptured_rows)
}

#' Aggregate Records into a Contingency Table. This function takes the row level
#' records produced by \code{build_individual_records} and aggregates identical
#' rows while appending a frequency column \code{N_ID}.
#'
#' @param records tibble: raw data where each row is an individual record with
#' capture and covariate category columns.
#' @return a contingency table tibble where identical rows in the input are
#' aggregated and a frequency column \code{N_ID} is appended.
#'
#' @importFrom dplyr count across everything
#' @export
build_contingency_table <- function(records) {
    return(count(records, across(everything()), name = "N_ID"))
}


#' Is Probability Vector
#' @description A function used to check if a vector is a valid probability
#' vector (i.e., numeric and all values between 0 and 1). This is used in the
#' validation of capture and category probabilities for data generation.
#' @param vec a vector to check
#' @returns a boolean indicating whether the vector is a valid probability
#' vector
#'
#' @keywords internal
#' @export
is_probability_vector <- function(vec) {
    if (!is.vector(vec)) {
        return(FALSE)
    }
    if (!is.numeric(vec)) {
        warning("Input vector must be numeric.")
        return(FALSE)
    }
    if (any(vec < 0 | vec > 1)) {
        warning("All values in the input vector must be between 0 and 1.")
        return(FALSE)
    }
    return(TRUE)
}

#' Is Probability Scalar
#' @description A function used to check if a value is a valid probability
#' scalar (i.e., numeric, length 1, and between 0 and 1). This is used in the
#' validation of capture and category probabilities for data generation when
#' the user specifies a single probability to be applied across all captures or
#' categories.
#' @param value a value to check
#' @returns a boolean indicating whether the value is a valid probability scalar
#'
#' @keywords internal
#' @export
is_probability_scalar <- function(value) {
    if (!is.numeric(value) || length(value) != 1) {
        warning("Input must be a numeric scalar.")
        return(FALSE)
    }
    if (value < 0 || value > 1) {
        warning("Input value must be between 0 and 1.")
        return(FALSE)
    }
    return(TRUE)
}

#' A function used to check if a column in a data frame is binary
#' (i.e., contains only 0s and 1s).
#'
#' @param column a vector representing a column in a data frame
#' @returns a boolean indicating whether the column is binary
#'
#' @keywords internal
#' @export
is_column_binary <- function(column) {
    unique_values <- unique(column)
    return(length(unique_values) == 2 && all(unique_values %in% c(0, 1)))
}

#' A function used to check if the provided data is a frequency table. This is
#' necessary as the CRC estimation functions require a frequency table as input.
#'
#' @param data a data frame
#' @param frequency_column a string specifying the name of the frequency column
#' in the data frame
#' @returns a boolean indicating whether the data frame is a frequency table
#' (i.e., contains the specified frequency column and that column is numeric)
#'
#' @keywords internal
#' @export
is_frequency_table <- function(data, frequency_column) {
    if (
        frequency_column %in%
            names(data) &&
            is.numeric(data[[frequency_column]])
    ) {
        return(TRUE)
    }
    return(FALSE)
}

#' A function used to convert all integer columns to numeric. This is necessary
#' as the drpop package requires all data columns to be numerics.
#' This is a temporary workaround until we can implement our own TMLE estimation
#' function that can handle integer columns.
#'
#' @param df a data frame
#' @returns a data frame with all integer columns converted to numeric
#'
#' @importFrom dplyr mutate across where
#' @keywords internal
#' @export
all_int_cols_to_numeric <- function(df) {
    return(mutate(df, across(where(is.integer), as.numeric)))
}

#' Build Individual Simulation Records. This builds all the individual records
#' for a simulated dataset. Each record produced by this function represents
#' one individual and contains the capture indicators and simulated numerical
#' covariate indicators. This function is traditionally wrapped by
#' \code{create_data} but
#' exposed for users who want more granular control over building the simulation
#' data. Importantly, the capture_probs and covariate_specs are not validated so
#' errors may not be as descriptive.
#'
#' @param n_individuals int: number of participants to simulate
#' @param capture_probs numeric vector: capture probabilities of length equal to
#'  the number of capture columns
#' @param covariate_specs data.frame: covariate specification table with one row
#' per covariate and columns \code{distribution}, \code{p1}, \code{p2}, and
#' \code{dtype}.
#' @returns a tibble where each row is an individual record
#'
#' @keywords internal
#' @export
build_individual_records <- function(
    n_individuals,
    capture_probs,
    covariate_specs
) {
    records <- purrr::map(
        seq_len(n_individuals),
        create_individual_record,
        capture_probs = capture_probs,
        covariate_specs = covariate_specs
    ) |>
        purrr::list_rbind()

    return(records)
}

#' Validate Inputs for create_data. This checks that all inputs are of the
#' correct type and value range. If any checks fail, an error is thrown.
#' Exclusively used within \code{create_data}.
#'
#' As this is a validation function with a lot of if checks, we ignore
#' cyclocomp_linter.
#'
#' @keywords internal
#' @noRd
# nolint start: cyclocomp_linter
validate_create_args <- function(
    n_individuals,
    n_captures,
    covariate_ranges,
    return_frequency_table
) {
    if (!is.numeric(n_individuals) || length(n_individuals) != 1) {
        stop("n_individuals must be a numeric scalar")
    }
    if (!is.numeric(n_captures) || length(n_captures) != 1) {
        stop("n_captures must be a numeric scalar")
    }
    if (n_individuals < 1 || n_individuals %% 1 != 0) {
        stop("n_individuals must be a positive integer")
    }
    if (n_captures < 1 || n_captures %% 1 != 0) {
        stop("n_captures must be a positive integer")
    }
    if (!is.null(covariate_ranges) && !is.data.frame(covariate_ranges)) {
        stop("covariate_ranges must be a data.frame or NULL")
    }
    if (
        !is.logical(return_frequency_table) ||
            length(return_frequency_table) != 1
    ) {
        stop("return_frequency_table must be a logical scalar")
    }

    return(invisible(NULL))
}
# nolint end: cyclocomp_linter

#' Normalize Capture Probabilities. This first checks that the capture
#' probabilities are specified and if not returns the default
#' (0.5 for each capture column). If probabilities are specified, this checks
#' that they are numeric, of the correct length, and between 0 and 1. If any
#' checks fail, an error is thrown. This is an internal function used within
#' \code{create_data}.
#'
#' @keywords internal
#' @noRd
normalize_p_captures <- function(n_captures, p_captures) {
    if (is.null(p_captures)) {
        return(rep(0.5, n_captures))
    }

    if (!is.numeric(p_captures)) {
        stop("p_captures must be a numeric vector")
    }
    if (length(p_captures) != n_captures) {
        stop("Length of p_captures must equal n_captures")
    }
    if (any(p_captures < 0 | p_captures > 1)) {
        stop("All p_captures values must be between 0 and 1")
    }

    return(as.numeric(p_captures))
}

#' Normalize Covariate Specifications. This validates and standardizes
#' \code{covariate_ranges} for use in \code{create_data}. The expected columns
#' are \code{distribution}, \code{p1}, \code{p2}, and \code{dtype}, where each
#' row defines one generated covariate.
#'
#' As this is a validation function with a lot of if checks, we ignore
#' cyclocomp_linter.
#'
#' @keywords internal
#' @noRd
# nolint start: cyclocomp_linter
normalize_covariate_ranges <- function(covariate_ranges) {
    if (is.null(covariate_ranges)) {
        return(data.frame(
            distribution = character(0),
            p1 = numeric(0),
            p2 = numeric(0),
            dtype = character(0)
        ))
    }

    required_columns <- c("distribution", "p1", "p2", "dtype")
    if (!all(required_columns %in% names(covariate_ranges))) {
        stop(
            paste(
                "covariate_ranges must contain columns:",
                "distribution, p1, p2, dtype"
            )
        )
    }

    covariate_specs <- covariate_ranges[, required_columns, drop = FALSE]

    if (nrow(covariate_specs) == 0) {
        return(covariate_specs)
    }

    covariate_specs[["distribution"]] <- tolower(as.character(
        covariate_specs[["distribution"]]
    ))
    covariate_specs[["dtype"]] <- tolower(as.character(covariate_specs[[
        "dtype"
    ]]))

    invalid_distributions <- setdiff(
        unique(covariate_specs[["distribution"]]),
        c("uniform", "normal")
    )
    if (length(invalid_distributions) > 0) {
        stop("distribution must be one of: uniform, normal")
    }

    invalid_dtypes <- setdiff(
        unique(covariate_specs[["dtype"]]),
        c("numeric", "integer")
    )
    if (length(invalid_dtypes) > 0) {
        stop("dtype must be one of: numeric, integer")
    }

    if (
        !is.numeric(covariate_specs[["p1"]]) ||
            !is.numeric(covariate_specs[["p2"]])
    ) {
        stop("p1 and p2 must be numeric")
    }
    if (any(is.na(covariate_specs[["p1"]]) | is.na(covariate_specs[["p2"]]))) {
        stop("p1 and p2 cannot contain NA values")
    }

    uniform_rows <- covariate_specs[["distribution"]] == "uniform"
    if (
        any(
            covariate_specs[["p1"]][uniform_rows] >
                covariate_specs[["p2"]][uniform_rows]
        )
    ) {
        stop("For uniform, p1 (low) must be <= p2 (high)")
    }

    normal_rows <- covariate_specs[["distribution"]] == "normal"
    if (any(covariate_specs[["p2"]][normal_rows] <= 0)) {
        stop("For normal, p2 (standard deviation) must be > 0")
    }

    return(covariate_specs)
}
# nolint end: cyclocomp_linter

#' Create One Individual Simulation Record. This simulates a single record of
#' data for one individual, including the capture indicators and numerical
#' covariates. The return type is a tibble row.
#' This is an internal function used within \code{build_individual_records}.
#'
#' @keywords internal
#' @noRd
create_individual_record <- function(index, capture_probs, covariate_specs) {
    invisible(index)
    capture_values <- create_capture(capture_probs)
    covariate_values <- sample_covariate_values(covariate_specs)

    record_values <- as.list(capture_values)
    record_values <- c(record_values, covariate_values)

    return(tibble::as_tibble_row(record_values))
}

#' A function to generate binomial flips along the probability specified
#'
#' @param prob numeric vector: probabilities respective to each \code{n}
#'
#' @importFrom stats rbinom
#' @keywords internal
#' @noRd
create_capture <- function(prob) {
    n <- length(prob)
    out <- as.integer(stats::rbinom(n = n, size = 1, prob = prob))
    names(out) <- paste0("capture_", 1:n)
    return(out)
}

#' Sample numerical covariate values for one individual
#'
#' @importFrom stats runif rnorm
#'
#' @keywords internal
#' @noRd
sample_covariate_values <- function(covariate_specs) {
    n <- nrow(covariate_specs)
    if (n == 0) {
        return(list())
    }

    values <- vector("list", n)
    for (i in seq_len(n)) {
        values[[i]] <- sample_covariate_value(covariate_specs[
            i,
            ,
            drop = FALSE
        ])
    }
    names(values) <- paste0("covariate_", seq_len(n))

    return(values)
}

sample_default_covariate <- function() {
    default_spec <- data.frame(
        distribution = "uniform",
        p1 = 0,
        p2 = 1,
        dtype = "integer"
    )
    return(sample_covariate_value(default_spec))
}

#' Sample one numerical covariate value from a specification row
#'
#' @importFrom stats runif rnorm
#' @keywords internal
#' @noRd
sample_covariate_value <- function(covariate_spec_row) {
    distribution <- covariate_spec_row[["distribution"]][[1]]
    p1 <- covariate_spec_row[["p1"]][[1]]
    p2 <- covariate_spec_row[["p2"]][[1]]
    dtype <- covariate_spec_row[["dtype"]][[1]]

    if (distribution == "uniform") {
        value <- stats::runif(n = 1, min = p1, max = p2)
    } else if (distribution == "normal") {
        value <- stats::rnorm(n = 1, mean = p1, sd = p2)
    } else {
        stop("Unsupported distribution in covariate specification")
    }

    if (dtype == "integer") {
        return(as.integer(round(value)))
    }

    out <- as.numeric(value)
    return(out)
}
