---
title: "DR-POP Analysis"
author:
    - name: "Matthew Carroll"
---

```{r}
library(crcsim)
library(drpop)
library(dplyr)
```

# Create Data

```{r}
set.seed(2024)
n_individuals <- 300000
n_captures <- 6
p_captures <- c(0.45, 0.35, 0.25, 0.20, 0.4, 0.1)
covariate_df <- data.frame(
    distribution = c("uniform", "uniform"),
    p1 = c(0, 0),
    p2 = c(1, 1),
    dtype = c("integer", "integer")
)

captures <- c(
    "capture_1", "capture_2", "capture_3",
    "capture_4", "capture_5", "capture_6"
)

sim_data <- create_data(
    n_individuals = n_individuals,
    n_captures = n_captures,
    p_captures = p_captures,
    covariate_ranges = covariate_df
) |>
    all_int_cols_to_numeric() |>
    extract_captured_data(captures)

no_cov_sim_data <- sim_data |>
    select(-covariate_1, -covariate_2) |>
    build_contingency_table()

known_pop_size <- nrow(sim_data)
```

# TMLE, DR, and PI Analysis

```{r}
qhat <- drpop::popsize(
    data = sim_data, funcname = c("logit"), nfolds = 2, margin = 0.005
)

psin_estimates <- drpop::popsize(
    data = sim_data, getnuis = qhat$nuis, idfold = qhat$idfold
)$result

drpop_df <- dplyr::select(psin_estimates, c("method", "n", "cin.l", "cin.u")) |> dplyr::rename(
    estimate = n,
    lower_ci = cin.l,
    upper_ci = cin.u
)
```

# Stepwise and AIC

```{r}
aic_options <- AICOptions$new(
    model = c("poisson"),
    capture_columns = captures,
)

step_options <- StepwiseOptions$new(
    model = c("poisson"),
    capture_columns = captures,
    threshold = c(0.005),
    direction = "both",
    frequency_col_name = "N_ID",
    interaction_limit = 2
)

aic_results <- crc(no_cov_sim_data, aic_options)
step_results <- crc(no_cov_sim_data, step_options)

selection_df <- data.frame(
    method = c("AIC-Poisson", "Stepwise-Poisson"),
    estimate = c(aic_results[1, ]$estimate + known_pop_size, step_results$estimate + known_pop_size),
    lower_ci = c(aic_results[1, ]$lower_ci + known_pop_size, step_results$lower_ci + known_pop_size),
    upper_ci = c(aic_results[1, ]$upper_ci + known_pop_size, step_results$upper_ci + known_pop_size)
)
```

# Negbin

```{r}
aic_options <- AICOptions$new(
    model = c("negbin"),
    capture_columns = captures,
)

step_options <- StepwiseOptions$new(
    model = c("negbin"),
    capture_columns = captures,
    threshold = c(0.005),
    direction = "both",
    frequency_col_name = "N_ID",
    interaction_limit = 2
)

aic_nb_results <- crc(no_cov_sim_data, aic_options)
step_nb_results <- crc(no_cov_sim_data, step_options)

selection_nb_df <- data.frame(
    method = c("AIC-Negbin", "Stepwise-Negbin"),
    estimate = c(aic_nb_results[1, ]$estimate + known_pop_size, step_nb_results$estimate + known_pop_size),
    lower_ci = c(aic_nb_results[1, ]$lower_ci + known_pop_size, step_nb_results$lower_ci + known_pop_size),
    upper_ci = c(aic_nb_results[1, ]$upper_ci + known_pop_size, step_nb_results$upper_ci + known_pop_size)
)

combo <- bind_rows(selection_df, selection_nb_df)
```

# Results

```{r}
library(ggplot2)
final_results <- bind_rows(drpop_df, combo)

p <- ggplot(final_results, aes(x = method, y = estimate)) +
    geom_point() +
    geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.2) +
    geom_hline(yintercept = 1.0, linetype = "dashed", color = "red") +
    labs(
        title = "Percent Relative Biases of Population Estimates",
        x = "Method",
        y = "Percent Relative Biases"
    ) +
    theme_minimal()
```