################################################################################
# File: create.R                                                               #
# Project: crc-sim                                                             #
# Created Date: 2026-02-17                                                     #
# Author: Matthew Carroll                                                      #
# -----                                                                        #
# Last Modified: 2026-05-14                                                    #
# Modified By: Matthew Carroll                                                 #
# -----                                                                        #
# Copyright (c) 2026 Syndemics Lab at Boston Medical Center                    #
################################################################################

#' Data generation tool. This creates a simulated dataset for testing various
#' Capture-Recapture models. The user is able to specify the number of
#' individuals, the number of captures, the number of covariate categories
#' (we currently assume all covariates are one-hot encoded category covariates),
#' the probabilities of capture for each capture column, and the probabilities
#' of category assignment for each category column. The returned value
#' represents the "raw" simulated data where each row is a single sample.
#' Frequency tables can also be generated by setting
#' \code{return_frequency_table} to \code{TRUE}, which will aggregate identical
#' rows and append a frequency column \code{N_ID}.
#'
#' @param n_individuals int: number of participants to simulate
#' @param n_captures int: number of binary capture columns to simulate
#' @param n_categories int: number of one-hot category columns to simulate
#' @param p_captures numeric vector: optional capture probabilities of length
#'   \code{n_captures}. Defaults to 0.5 for each capture column.
#' @param p_categories numeric vector: optional category probabilities of length
#'   \code{n_categories}. Must sum to 1. Defaults to category_1 = 1.
#' @param return_frequency_table logical: when \code{TRUE}, aggregates identical
#'   rows and appends frequency column \code{N_ID}. Default is \code{FALSE}.
#'
#' @returns a tibble
#'
#' @export
create_data <- function(
    n_individuals,
    n_captures,
    n_categories = 1,
    p_captures = NULL,
    p_categories = NULL,
    return_frequency_table = FALSE
) {
    validate_create_args(
        n_individuals = n_individuals,
        n_captures = n_captures,
        n_categories = n_categories,
        return_frequency_table = return_frequency_table
    )

    capture_probs <- normalize_p_captures(
        n_captures = n_captures,
        p_captures = p_captures
    )

    category_probs <- normalize_p_categories(
        n_categories = n_categories,
        p_categories = p_categories
    )

    records <- build_individual_records(
        n_individuals = n_individuals,
        capture_probs = capture_probs,
        category_probs = category_probs
    )

    if (isTRUE(return_frequency_table)) {
        return(build_contingency_table(records))
    }

    return(records)
}


#' Build Individual Simulation Records. This builds all the individual records
#' for a simulated dataset. Each record produced by this function represents
#' one individual and contains the capture indicators and one-hot category
#' indicators. This function is traditionally wrapped by \code{create_data} but
#' exposed for users who want more granular control over building the simulation
#' data. Importantly, the capture_probs and category_probs are not validated so
#' errors may not be as descriptive.
#'
#' @param n_individuals int: number of participants to simulate
#' @param capture_probs numeric vector: capture probabilities of length equal to
#'  the number of capture columns
#' @param category_probs numeric vector: category probabilities of length equal
#' to the number of category columns. Must sum to 1.
#' @returns a tibble where each row is an individual record
#'
#' @export
build_individual_records <- function(
    n_individuals,
    capture_probs,
    category_probs
) {
    records <- purrr::map(
        seq_len(n_individuals),
        create_individual_record,
        capture_probs = capture_probs,
        category_probs = category_probs
    ) |>
        purrr::list_rbind()

    return(records)
}

#' Aggregate Records into a Contingency Table. This function takes the row level
#' records produced by \code{build_individual_records} and aggregates identical
#' rows while appending a frequency column \code{N_ID}.
#'
#' @param records tibble: raw data where each row is an individual record with
#' capture and covariate category columns.
#' @return a contingency table tibble where identical rows in the input are
#' aggregated and a frequency column \code{N_ID} is appended.
#'
#' @importFrom dplyr count across everything
#' @export
build_contingency_table <- function(records) {
    return(count(records, across(everything()), name = "N_ID"))
}

#' Validate Inputs for create_data. This checks that all inputs are of the
#' correct type and value range. If any checks fail, an error is thrown.
#' Exclusively used within \code{create_data}.
#'
#' @keywords internal
#' @noRd
validate_create_args <- function(
    n_individuals,
    n_captures,
    n_categories,
    return_frequency_table
) {
    if (!is.numeric(n_individuals) || length(n_individuals) != 1) {
        stop("n_individuals must be a numeric scalar")
    }
    if (!is.numeric(n_captures) || length(n_captures) != 1) {
        stop("n_captures must be a numeric scalar")
    }
    if (!is.numeric(n_categories) || length(n_categories) != 1) {
        stop("n_categories must be a numeric scalar")
    }

    if (n_individuals < 1 || n_individuals %% 1 != 0) {
        stop("n_individuals must be a positive integer")
    }
    if (n_captures < 1 || n_captures %% 1 != 0) {
        stop("n_captures must be a positive integer")
    }
    if (n_categories < 1 || n_categories %% 1 != 0) {
        stop("n_categories must be a positive integer")
    }
    if (
        !is.logical(return_frequency_table) ||
            length(return_frequency_table) != 1
    ) {
        stop("return_frequency_table must be a logical scalar")
    }

    return(invisible(NULL))
}

#' Normalize Capture Probabilities. This first checks that the capture
#' probabilities are specified and if not returns the default
#' (0.5 for each capture column). If probabilities are specified, this checks
#' that they are numeric, of the correct length, and between 0 and 1. If any
#' checks fail, an error is thrown. This is an internal function used within
#' \code{create_data}.
#'
#' @keywords internal
#' @noRd
normalize_p_captures <- function(n_captures, p_captures) {
    if (is.null(p_captures)) {
        return(rep(0.5, n_captures))
    }

    if (!is.numeric(p_captures)) {
        stop("p_captures must be a numeric vector")
    }
    if (length(p_captures) != n_captures) {
        stop("Length of p_captures must equal n_captures")
    }
    if (any(p_captures < 0 | p_captures > 1)) {
        stop("All p_captures values must be between 0 and 1")
    }

    return(as.numeric(p_captures))
}

#' Normalize Category Probabilities. This first checks that the category
#' probabilities are specified and if not returns the default (category_1 = 1).
#' If probabilities are specified, this checks that they are numeric, of the
#' correct length, between 0 and 1, and sum to 1. If any checks fail, an error
#' is thrown. This is an internal function used within \code{create_data}.
#'
#' @keywords internal
#' @noRd
normalize_p_categories <- function(n_categories, p_categories) {
    if (is.null(p_categories)) {
        default_probs <- rep(0, n_categories)
        default_probs[1] <- 1

        return(default_probs)
    }

    if (!is.numeric(p_categories)) {
        stop("p_categories must be a numeric vector")
    }
    if (length(p_categories) != n_categories) {
        stop("Length of p_categories must equal n_categories")
    }
    if (any(p_categories < 0 | p_categories > 1)) {
        stop("All p_categories values must be between 0 and 1")
    }
    if (!isTRUE(all.equal(sum(p_categories), 1))) {
        stop("p_categories must sum to 1")
    }

    return(as.numeric(p_categories))
}

#' Create One Individual Simulation Record. This simulates a single record of
#' data for one individual, including the capture indicators and one-hot
#' category covariate indicators. The return type is a tibble row.
#' This is an internal function used within \code{build_individual_records}.
#'
#' @keywords internal
#' @noRd
create_individual_record <- function(index, capture_probs, category_probs) {
    invisible(index)
    capture_values <- create_capture(capture_probs)
    category_values <- create_category_one_hot(category_probs)

    return(tibble::as_tibble_row(c(capture_values, category_values)))
}

#' A function to generate binomial flips along the probability specified
#'
#' @param prob numeric vector: probabilities respective to each \code{n}
#'
#' @importFrom stats rbinom
#' @keywords internal
#' @noRd
create_capture <- function(prob) {
    n <- length(prob)
    out <- as.integer(stats::rbinom(n = n, size = 1, prob = prob))
    names(out) <- paste0("capture_", 1:n)
    return(out)
}

#' Create one-hot category indicator
#'
#' @param prob numeric vector: category probabilities of n
#'
#' @keywords internal
#' @noRd
create_category_one_hot <- function(prob) {
    n <- length(prob)
    sampled_category <- sample(1:n, 1, prob = prob)
    out <- as.integer(seq_len(n) == sampled_category)
    names(out) <- paste0("category_", 1:n)
    return(out)
}
