---
title: Dependencies
author: Matthew Carroll
---

In order to estimate the unknown prevalence, we need to consider the dependencies between various factors that influence the outcome. These dependencies can be represented using statistical models or probabilistic frameworks that capture the relationships between the variables of interest. Given the HIPPA restrictions in this data, we are only allowed to use aggregated data outside the Department of Public Health. Internally, however, code packages can access more granular data. Thus, we must be able to design a package that can handle both aggregated and individual level data and check for dependencies accurately. Our data is presented as a set of datasets and covariates, where each dataset contains observations for a specific set of variables, and covariates represent the attributes or characteristics associated with each observation. From this data, we shall check for the following dependencies:

- Conditional dependencies between each list.
  -  
- Correlations between different lists of variables.